# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_window_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindowBase(object):
    def setupUi(self, MainWindowBase):
        MainWindowBase.setObjectName("MainWindowBase")
        MainWindowBase.resize(585, 628)
        MainWindowBase.setWindowOpacity(4.0)
        self.centralwidget = QtWidgets.QWidget(MainWindowBase)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 561, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(10, 106, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 350, 541, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.save = QtWidgets.QPushButton(self.tab)
        self.save.setGeometry(QtCore.QRect(460, 460, 75, 23))
        self.save.setObjectName("save")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 140, 511, 192))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.organizationIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.organizationIDLabel.setObjectName("organizationIDLabel")
        self.verticalLayout.addWidget(self.organizationIDLabel)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.org_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.org_id.setObjectName("org_id")
        self.verticalLayout_2.addWidget(self.org_id)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.technicalAccountIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.technicalAccountIDLabel.setObjectName("technicalAccountIDLabel")
        self.verticalLayout_4.addWidget(self.technicalAccountIDLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tech_acct_id = QtWidgets.QLineEdit(self.layoutWidget)
        self.tech_acct_id.setObjectName("tech_acct_id")
        self.verticalLayout_5.addWidget(self.tech_acct_id)
        self.gridLayout_2.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2.addLayout(self.verticalLayout_6, 1, 2, 1, 1)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.aPIKeyClientIDLabel = QtWidgets.QLabel(self.layoutWidget)
        self.aPIKeyClientIDLabel.setObjectName("aPIKeyClientIDLabel")
        self.verticalLayout_25.addWidget(self.aPIKeyClientIDLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_25, 2, 0, 1, 1)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.api_key = QtWidgets.QLineEdit(self.layoutWidget)
        self.api_key.setObjectName("api_key")
        self.verticalLayout_26.addWidget(self.api_key)
        self.gridLayout_2.addLayout(self.verticalLayout_26, 2, 1, 1, 1)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.gridLayout_2.addLayout(self.verticalLayout_27, 2, 2, 1, 1)
        self.verticalLayout_28 = QtWidgets.QVBoxLayout()
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.clientSecretLabel = QtWidgets.QLabel(self.layoutWidget)
        self.clientSecretLabel.setObjectName("clientSecretLabel")
        self.verticalLayout_28.addWidget(self.clientSecretLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_28, 3, 0, 1, 1)
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.client_secret = QtWidgets.QLineEdit(self.layoutWidget)
        self.client_secret.setObjectName("client_secret")
        self.verticalLayout_29.addWidget(self.client_secret)
        self.gridLayout_2.addLayout(self.verticalLayout_29, 3, 1, 1, 1)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.gridLayout_2.addLayout(self.verticalLayout_30, 3, 2, 1, 1)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.hostLabel = QtWidgets.QLabel(self.layoutWidget)
        self.hostLabel.setObjectName("hostLabel")
        self.verticalLayout_31.addWidget(self.hostLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_31, 4, 0, 1, 1)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.host = QtWidgets.QLineEdit(self.layoutWidget)
        self.host.setObjectName("host")
        self.verticalLayout_32.addWidget(self.host)
        self.gridLayout_2.addLayout(self.verticalLayout_32, 4, 1, 1, 1)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.gridLayout_2.addLayout(self.verticalLayout_33, 4, 2, 1, 1)
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.imsHostLabel = QtWidgets.QLabel(self.layoutWidget)
        self.imsHostLabel.setObjectName("imsHostLabel")
        self.verticalLayout_34.addWidget(self.imsHostLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_34, 5, 0, 1, 1)
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.ims_host = QtWidgets.QLineEdit(self.layoutWidget)
        self.ims_host.setObjectName("ims_host")
        self.verticalLayout_35.addWidget(self.ims_host)
        self.gridLayout_2.addLayout(self.verticalLayout_35, 5, 1, 1, 1)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.gridLayout_2.addLayout(self.verticalLayout_36, 5, 2, 1, 1)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.privateKeyFileLabel = QtWidgets.QLabel(self.layoutWidget)
        self.privateKeyFileLabel.setObjectName("privateKeyFileLabel")
        self.verticalLayout_37.addWidget(self.privateKeyFileLabel)
        self.gridLayout_2.addLayout(self.verticalLayout_37, 6, 0, 1, 1)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.private_key_file = QtWidgets.QLineEdit(self.layoutWidget)
        self.private_key_file.setObjectName("private_key_file")
        self.verticalLayout_38.addWidget(self.private_key_file)
        self.gridLayout_2.addLayout(self.verticalLayout_38, 6, 1, 1, 1)
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.privateKeyPath = QtWidgets.QToolButton(self.layoutWidget)
        self.privateKeyPath.setObjectName("privateKeyPath")
        self.verticalLayout_39.addWidget(self.privateKeyPath)
        self.gridLayout_2.addLayout(self.verticalLayout_39, 6, 2, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 380, 511, 74))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.logon_type = QtWidgets.QLineEdit(self.layoutWidget1)
        self.logon_type.setObjectName("logon_type")
        self.gridLayout.addWidget(self.logon_type, 1, 1, 1, 1)
        self.id_type = QtWidgets.QLineEdit(self.layoutWidget1)
        self.id_type.setObjectName("id_type")
        self.gridLayout.addWidget(self.id_type, 0, 1, 1, 1)
        self.idTypeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.idTypeLabel.setObjectName("idTypeLabel")
        self.gridLayout.addWidget(self.idTypeLabel, 0, 0, 1, 1)
        self.logonTypeLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.logonTypeLabel.setObjectName("logonTypeLabel")
        self.gridLayout.addWidget(self.logonTypeLabel, 1, 0, 1, 1)
        self.userNameFileLabel = QtWidgets.QLabel(self.layoutWidget1)
        self.userNameFileLabel.setObjectName("userNameFileLabel")
        self.gridLayout.addWidget(self.userNameFileLabel, 2, 0, 1, 1)
        self.users_filename = QtWidgets.QLineEdit(self.layoutWidget1)
        self.users_filename.setObjectName("users_filename")
        self.gridLayout.addWidget(self.users_filename, 2, 1, 1, 1)
        self.userListFilePath = QtWidgets.QToolButton(self.layoutWidget1)
        self.userListFilePath.setObjectName("userListFilePath")
        self.gridLayout.addWidget(self.userListFilePath, 2, 2, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 70, 511, 24))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.config_File_name = QtWidgets.QLineEdit(self.layoutWidget2)
        self.config_File_name.setObjectName("config_File_name")
        self.verticalLayout_7.addWidget(self.config_File_name)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.configFilePath = QtWidgets.QToolButton(self.layoutWidget2)
        self.configFilePath.setObjectName("configFilePath")
        self.verticalLayout_8.addWidget(self.configFilePath)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        self.message = QtWidgets.QLabel(self.tab)
        self.message.setGeometry(QtCore.QRect(10, 13, 541, 21))
        self.message.setText("")
        self.message.setObjectName("message")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 541, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label.raise_()
        self.save.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.message.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.run_user_update = QtWidgets.QPushButton(self.tab_2)
        self.run_user_update.setGeometry(QtCore.QRect(440, 100, 91, 31))
        self.run_user_update.setObjectName("run_user_update")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 141, 21))
        self.label_6.setObjectName("label_6")
        self.config_File_name_readOnly = QtWidgets.QLineEdit(self.tab_2)
        self.config_File_name_readOnly.setGeometry(QtCore.QRect(190, 50, 341, 20))
        self.config_File_name_readOnly.setObjectName("config_File_name_readOnly")
        self.console_log = QtWidgets.QTextBrowser(self.tab_2)
        self.console_log.setGeometry(QtCore.QRect(30, 171, 501, 281))
        self.console_log.setObjectName("console_log")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(30, 135, 111, 21))
        self.label_5.setObjectName("label_5")
        self.message_UpdUser_tab = QtWidgets.QLabel(self.tab_2)
        self.message_UpdUser_tab.setGeometry(QtCore.QRect(10, 10, 541, 21))
        self.message_UpdUser_tab.setText("")
        self.message_UpdUser_tab.setObjectName("message_UpdUser_tab")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindowBase.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowBase)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        MainWindowBase.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowBase)
        self.statusbar.setObjectName("statusbar")
        MainWindowBase.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindowBase)

    def retranslateUi(self, MainWindowBase):
        _translate = QtCore.QCoreApplication.translate
        MainWindowBase.setWindowTitle(_translate("MainWindowBase", "Admin Console User Update Tool"))
        self.label.setText(_translate("MainWindowBase", " UMAPI Configurations"))
        self.label_2.setText(_translate("MainWindowBase", " User Configurations"))
        self.save.setText(_translate("MainWindowBase", "Save"))
        self.organizationIDLabel.setText(_translate("MainWindowBase", "Organization ID"))
        self.technicalAccountIDLabel.setText(_translate("MainWindowBase", "Technical account ID"))
        self.aPIKeyClientIDLabel.setText(_translate("MainWindowBase", "API Key (Client ID)"))
        self.clientSecretLabel.setText(_translate("MainWindowBase", "Client secret"))
        self.hostLabel.setText(_translate("MainWindowBase", "Host"))
        self.imsHostLabel.setText(_translate("MainWindowBase", "ims Host"))
        self.privateKeyFileLabel.setText(_translate("MainWindowBase", "Private Key File"))
        self.privateKeyPath.setText(_translate("MainWindowBase", "..."))
        self.idTypeLabel.setText(_translate("MainWindowBase", "Id Type"))
        self.logonTypeLabel.setText(_translate("MainWindowBase", "Logon Type"))
        self.userNameFileLabel.setText(_translate("MainWindowBase", "User Name File  "))
        self.userListFilePath.setText(_translate("MainWindowBase", "..."))
        self.label_3.setText(_translate("MainWindowBase", "Configuration File Path    "))
        self.configFilePath.setText(_translate("MainWindowBase", "..."))
        self.label_4.setText(_translate("MainWindowBase", " Configuration File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindowBase", "Configuration"))
        self.run_user_update.setText(_translate("MainWindowBase", "Update Users"))
        self.label_6.setText(_translate("MainWindowBase", "Configuration File Path :   "))
        self.label_5.setText(_translate("MainWindowBase", "Run Log"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindowBase", "Update Users"))

